# Generated by Django 5.2.11 on 2026-02-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='resume_path',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
