# Generated by Django 5.2.11 on 2026-02-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verified_user_mfa_enabled_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/cover_photos/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/cover_photos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/profile_pictures/'),
        ),
    ]
