# Generated by Django 5.2.11 on 2026-02-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_candidate_cover_photo_candidate_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True, help_text='Professional summary or bio'),
        ),
    ]
