# Generated by Django 5.2.11 on 2026-02-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Job title/position', max_length=255)),
                ('is_current', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='accounts.candidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.organization')),
            ],
            options={
                'ordering': ['-is_current', '-start_date'],
                'indexes': [models.Index(fields=['candidate', 'is_current'], name='accounts_em_candida_d595a9_idx'), models.Index(fields=['organization', 'is_current'], name='accounts_em_organiz_40018e_idx')],
            },
        ),
    ]
