# Generated by Django 5.2.11 on 2026-02-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_talentpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this employment is visible on public profiles'),
        ),
    ]
