# Generated by Django 5.2.11 on 2026-03-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_requests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_status_9f0685_idx',
            old_name='chat_conver_status_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
