// import { useMemo } from "react";
// import { useInternetIdentity } from "./useInternetIdentity";

// // 👇 GENERATED by dfx (already in your project)
// import { backend } from "../../../declarations/backend";

// export function useActor() {
//   const { identity } = useInternetIdentity();

//   const actor = useMemo(() => {
//     if (!identity) return backend;

//     return backend.withOptions({
//       agentOptions: {
//         identity,
//       },
//     });
//   }, [identity]);

//   return actor;
// }
