# Generated by Django 5.2.10 on 2026-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_application_category_application_final_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='requirements',
            new_name='education_required',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_title_aliases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='max_experience_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='min_experience_years',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='required_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('highly_preferred', 'Highly Preferred (60-100)'), ('mid_preference', 'Mid Preference (50-60)'), ('low_preference', 'Low Preference (25-50)'), ('no_visit', "Don't Need to Visit (0-25)")], default='no_visit', max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='final_score',
            field=models.FloatField(default=0.0),
        ),
    ]
