# Generated by Django 5.2.11 on 2026-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidate_summary'),
        ('vacancies', '0008_application_is_self_test_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('is_self_test', False)), fields=('vacancy', 'candidate'), name='unique_application_per_candidate'),
        ),
    ]
