# Generated by Django 5.2.11 on 2026-02-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_follow'),
        ('vacancies', '0009_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='accounts.candidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_offers', to='accounts.organization')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='vacancies.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vacancy', 'candidate')},
            },
        ),
    ]
