# Generated by Django 6.0.1 on 2026-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('highly_preferred', 'Highly Preferred (60-70+)'), ('mid_preference', 'Mid Preference (50-60)'), ('low_preference', 'Low Preference (25-50)'), ('no_visit', "Don't Need to Visit (0-25)")], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
