# Generated by Django 5.2.11 on 2026-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_application_ml_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='passcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
