# Generated by Django 5.2.11 on 2026-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_self_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='self_test_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
