# Generated by Django 5.2.11 on 2026-02-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_employment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_pools', to='accounts.candidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_pool_members', to='accounts.organization')),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='accounts_ta_organiz_0d80c3_idx'), models.Index(fields=['candidate', 'is_active'], name='accounts_ta_candida_dfed34_idx'), models.Index(fields=['joined_at'], name='accounts_ta_joined__dbdb0f_idx')],
                'unique_together': {('candidate', 'organization')},
            },
        ),
    ]
