# Generated by Django 5.2.11 on 2026-03-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_credentials',
            field=models.TextField(blank=True, help_text='JSON string of Google OAuth credentials', null=True),
        ),
    ]
